env:
  es6: true
  node: true
  googleappsscript/googleappsscript: true
extends:
  - airbnb-base
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript # this line does the trick
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  Todoist: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - '@typescript-eslint'
  - googleappsscript
ignorePatterns:
  - '*.js'
  - '*.d.ts'
rules:
  "@typescript-eslint/naming-convention": [
    error,
    { selector: default, format: [camelCase] },
    { selector: variable, format: [camelCase, UPPER_CASE] },
    { selector: parameter, format: [camelCase], leadingUnderscore: allow },
    { selector: memberLike, modifiers: [private], format: [camelCase] },
    { selector: memberLike, modifiers: [static, readonly], format: [UPPER_CASE] },
    { selector: typeLike, format: [PascalCase] }
  ]
  '@typescript-eslint/no-unused-vars': error
  camelcase: off
  import/extensions: [error, ignorePackages, { ts: never, js: never }]
  import/prefer-default-export: off
  lines-between-class-members: [error, always, { exceptAfterSingleLine: true }]
  no-console: [error, { allow: [info, warn, error] }]
  no-underscore-dangle: [error, { allowAfterThis: true }]
  no-unused-vars: off
